// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gpu_profiling.proto

#include "gpu_profiling.pb.h"
#include "gpu_profiling.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace gpuprofiling {

static const char* GPUProfilingService_method_names[] = {
  "/gpuprofiling.GPUProfilingService/PerformGPUProfiling",
};

std::unique_ptr< GPUProfilingService::Stub> GPUProfilingService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GPUProfilingService::Stub> stub(new GPUProfilingService::Stub(channel, options));
  return stub;
}

GPUProfilingService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_PerformGPUProfiling_(GPUProfilingService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GPUProfilingService::Stub::PerformGPUProfiling(::grpc::ClientContext* context, const ::gpuprofiling::GPUProfilingRequest& request, ::gpuprofiling::GPUProfilingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gpuprofiling::GPUProfilingRequest, ::gpuprofiling::GPUProfilingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PerformGPUProfiling_, context, request, response);
}

void GPUProfilingService::Stub::async::PerformGPUProfiling(::grpc::ClientContext* context, const ::gpuprofiling::GPUProfilingRequest* request, ::gpuprofiling::GPUProfilingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gpuprofiling::GPUProfilingRequest, ::gpuprofiling::GPUProfilingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PerformGPUProfiling_, context, request, response, std::move(f));
}

void GPUProfilingService::Stub::async::PerformGPUProfiling(::grpc::ClientContext* context, const ::gpuprofiling::GPUProfilingRequest* request, ::gpuprofiling::GPUProfilingResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PerformGPUProfiling_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gpuprofiling::GPUProfilingResponse>* GPUProfilingService::Stub::PrepareAsyncPerformGPUProfilingRaw(::grpc::ClientContext* context, const ::gpuprofiling::GPUProfilingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gpuprofiling::GPUProfilingResponse, ::gpuprofiling::GPUProfilingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PerformGPUProfiling_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gpuprofiling::GPUProfilingResponse>* GPUProfilingService::Stub::AsyncPerformGPUProfilingRaw(::grpc::ClientContext* context, const ::gpuprofiling::GPUProfilingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPerformGPUProfilingRaw(context, request, cq);
  result->StartCall();
  return result;
}

GPUProfilingService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GPUProfilingService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GPUProfilingService::Service, ::gpuprofiling::GPUProfilingRequest, ::gpuprofiling::GPUProfilingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GPUProfilingService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gpuprofiling::GPUProfilingRequest* req,
             ::gpuprofiling::GPUProfilingResponse* resp) {
               return service->PerformGPUProfiling(ctx, req, resp);
             }, this)));
}

GPUProfilingService::Service::~Service() {
}

::grpc::Status GPUProfilingService::Service::PerformGPUProfiling(::grpc::ServerContext* context, const ::gpuprofiling::GPUProfilingRequest* request, ::gpuprofiling::GPUProfilingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace gpuprofiling

